version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              CLUSTER='sample-webapp-cluster'
              FAMILY='nginx-sample-webapp'
              DOCKER_IMAGE='nginx-sample-webapp'
              TASK='nginx-sample-webapp'
              SERVICE='sample-webapp-service'
              # Login to AWS
              aws configure set region $AWS_REGION
              $(aws ecr get-login)
              # Tag and push docker image
              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              # Create task for docker deploy
              task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                  "essential": true,
                  "memoryReservation": 128,
                  "portMappings": [
                    {
                      "containerPort": 80,
                      "hostPort": 0
                    }
                  ],
                  "environment" : [
                      { "name" : "DOCKUID", "value" : "10004" },
                      { "name" : "DOCKGID", "value" : "10004" },
                      { "name" : "DOCKUNIWRK", "value" : "1" },
                      { "name" : "DOCKMEZPRT", "value" : "soylatte" },
                      { "name" : "DOCKPGHOST", "value" : "%s" },
                      { "name" : "DOCKPGPORT", "value" : "5432" },
                      { "name" : "DOCKPGDB", "value" : "$s" },
                      { "name" : "DOCKPGUSER", "value" : "%s" },
                      { "name" : "DOCKPGPASSWD", "value" : "%s" }
                  ]
                }
              ]'
              echo "$task_template"
              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1 $DOCKPGHOST $DOCKPGDB $DOCKPGUSER $DOCKPGPASSWD)
              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
              # Deploy revision
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi
