version: 2
jobs:
  build-app:
    working_directory: /app
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "app/staging" ]; then
              CLUSTER='sample-webapp-cluster'
              FAMILY='aws-steps-app'
              DOCKER_IMAGE='aws-steps/app'
              TASK='aws-steps-app'
              SERVICE='aws-steps-app-service'
              # Login to AWS
              aws configure set region $AWS_REGION
              $(aws ecr get-login)
              # Tag and push docker image
              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              # Create task for docker deploy
              task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                  "essential": true,
                  "memoryReservation": 512,
                  "portMappings": [
                    {
                      "containerPort": 8000,
                      "hostPort": 0
                    }
                  ],
                  "environment" : [
                      { "name" : "DEBUG", "value" : "False" },
                      { "name" : "DOCKPGHOST", "value" : "%s" },
                      { "name" : "DOCKPGPORT", "value" : "5432" },
                      { "name" : "DOCKPGDB", "value" : "soylatte" },
                      { "name" : "DOCKPGUSER", "value" : "postgres" },
                      { "name" : "DOCKPGPASSWD", "value" : "%s" },
                      { "name" : "SECRET_KEY", "value" : "$s" },
                      { "name" : "NEVERCACHE_KEY", "value" : "%s" }
                  ]
                }
              ]'
              echo "$task_template"
              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1 $DOCKPGHOST $DOCKPGPASSWD $SECRET_KEY $NEVERCACHE_KEY)
              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
              # Deploy revision
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi
  build-web:
    working_directory: /web
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run:
          name: Build web Docker image
          command: |
            docker build -t web .

      - deploy:
          name: Push web Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "web/staging" ]; then
              CLUSTER='sample-webapp-cluster'
              FAMILY='aws-steps-web'
              DOCKER_IMAGE='aws-steps/web'
              TASK='aws-steps-web'
              SERVICE='aws-steps-web-service'
              # Login to AWS
              aws configure set region $AWS_REGION
              $(aws ecr get-login)
              # Tag and push docker image
              docker tag web $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              # Create task for docker deploy
              task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                  "essential": true,
                  "memoryReservation": 128,
                  "portMappings": [
                    {
                      "containerPort": 80,
                      "hostPort": 0
                    }
                  ],
                  "environment" : [
                      { "name" : "NGINX_HOST", "value" : "%s" },
                      { "name" : "NGINX_PORT", "value" : "80" },
                      { "name" : "APP_HOST", "value" : "%s" },
                      { "name" : "APP_PORT", "value" : "8000" }
                  ]
                }
              ]'
              echo "$task_template"
              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1 $NGINX_HOST $APP_HOST)
              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
              # Deploy revision
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi

workflows:
  version: 2
  build-app_and_build-web:
    jobs:
      - build-app:
          filters:
            branches:
              only: /^app*/
      - build-web:
          filters:
            branches:
              only: /^web*/

